name 'feign'
maintainer 'Joseph J Nuspl Jr'
maintainer_email 'nuspl@nvwls.com'
license 'Apache-2.0'
description 'Feign support for kitchen testing'
version '0.1.1'
chef_version '>= 15.0'

issues_url 'https://github.com/nvwls/feign/issues'
source_url 'https://github.com/nvwls/feign'
